### ISSUE TITLE
Remove search terms for Youtube playlists

### ISSUE THREAD

**Issue by asetniop** [BobNisco/Spotlistr#14]
A lot of times extraneous terms in the video titles ("with lyrics", "by" "official video") cause songs to be missed in the search.  It might be worth to create a list of common terms like this and excise them before looking for matches; will increase the number of matched songs.

**Comment by BobNisco** [comment]
Fixed wit https://github.com/BobNisco/Spotlistr/commit/ace10bd75fad325814381361ed4eb3fb84a9aab0

**Comment by asetniop** [comment]
Looking good!  It's probably not worth the trouble, but an optional checklist of more broad terms to strip ("live", "remastered", "official", "audio") on the search page might be a nice addition.  In any case, thanks for the update!
