### ISSUE TITLE
support memes

### ISSUE THREAD

**Issue by mattrozak** [BobNisco/Spotlistr#15]
I would like to make Spotify playlists from a collection of memes.  I think a large majority of your customer base would also use this feature.

RIP Harambe 🐒

**Comment by mattrozak** [comment]
https://open.spotify.com/track/1jJKO1VHcDpzKcExYlzJ8b

**Comment by BobNisco** [comment]
🤔

**Comment by mattrozak** [comment]
The community has spoken and we still want spotlistr to support playlist generation from memes.
