### ISSUE TITLE
Last.FM similar track search doesn't work with large lists

### ISSUE THREAD

**Issue by michael73072** [BobNisco/Spotlistr#2]
I pasted in 137 songs into the Last.FM similar track generator, and it just hangs and says that none of the songs were found on Spotify. The button stays greyed out and says "Searching...". If I submit half of the songs, it works just fine. I'm thinking this might be a limitation of the Last.FM API, but I'm not sure. Adblock is disabled.

(I wanted to paste in an entire playlist to get some new suggestions in case you are wondering why I would want to do this.)

Screenshot: http://i.imgur.com/QSgrHXx.png

**Comment by BobNisco** [comment]
Thanks for this bug report. It should be fixed up now, try it again!
