### ISSUE TITLE
Search API now requires authentication

### ISSUE THREAD

**Issue by dotfield** [BobNisco/Spotlistr#23]
During the last week or so it has been changed such that search commands require authentication.

This is what you need to create a playlist and therefore it does not work.
All the items were returning no results.

**Comment by asetniop** [comment]
Yep, still persisting.

**Comment by BobNisco** [comment]
Fixed with https://github.com/BobNisco/Spotlistr/commit/73dc992ec7752317d6f82c7802450d3b3d419de9
