### ISSUE TITLE
Import / create playlist from list of Spotify IDs (or links)

### ISSUE THREAD

**Issue by valZho** [BobNisco/Spotlistr#24]
Spotlistr lets you export a playlist including the Spotify ID, but there's not a way to then reimport that list. Perhaps you want to copy someone else's playlist with some modifications or combine playlists easily. If the Textbox import (or something like it) could read Spotify IDs that would skip the whole lookup/choosing process.

Further, if an app has huge lists of songs and allows people to generate custom lists of Spotify IDs/links (e.g., RBDB.online), using those lists to create a Spotify playlist on Spotlistr would be much smoother without having to go through the song lookup and selection process (since the tracks have, essentially, already been looked up).

**Comment by BobNisco** [comment]
This is now implemented as you can now search as `isrc` values in the [textbox search](http://spotlistr.herokuapp.com/#/search/textbox). That is the only unique identifier that the Spotify Web API allows us to search with: https://developer.spotify.com/web-api/search-item/
