### ISSUE TITLE
YouTube import issues: deleted and private videos

### ISSUE THREAD

**Issue by hckr** [BobNisco/Spotlistr#32]
Private and deleted videos should be properly recognized.

Deleted videos are currently recognized as: 
![screenshot_20180310_030419](https://user-images.githubusercontent.com/1078650/37237120-e3dc35a6-240f-11e8-99bf-3525e5f3e7d7.png)

Private videos are recognized as ones with multiple matches (separately for each unavailable video):
![screenshot_20180310_030636](https://user-images.githubusercontent.com/1078650/37237151-267d0142-2410-11e8-9ee4-17b57bf4651e.png)

**Comment by BobNisco** [comment]
Given that Spotlistr doesn't have users log in via YouTube, it won't work with properly with private or deleted videos. I don't think this will be a thing that we will support given the complexity for very small return

**Comment by hckr** [comment]
I agree, but I just wanted to point out that current implementation could be changed to hide all private and deleted videos. Sorry, I should have written it explicitly.

**Comment by BobNisco** [comment]
Ah perhaps I misunderstood your suggestion. Thanks for the clarification, I'll see if we can handle this better.

**Comment by JakeSteam** [comment]
A potential workaround would be to only add each video to the playlist once. I just had to delete 100+ duplicate instances of the "skit Video has been deleted" and "Private Eyes"!

**Comment by JakeSteam** [comment]
Note that this pull request should fix this: https://github.com/BobNisco/Spotlistr/pull/35

**Comment by BobNisco** [comment]
Big thanks to @JakeSteam for fixing this. I have merged his PR and deployed it, it should be live https://spotlistr.herokuapp.com/#/search/youtube
