### ISSUE TITLE
How to run on Windows 10?

### ISSUE THREAD

**Issue by Suleman-Elahi** [BobNisco/Spotlistr#33]
I don't have much idea about Node or npm. But after following steps I encountered some problems.
The "npm run dev-server" doesn't work.!!!
![image](https://user-images.githubusercontent.com/24384996/37240376-37b8545e-23ff-11e8-8ebb-91a3e5413954.png)

Any ideas how to fix this ?

**Comment by BobNisco** [comment]
Admittedly, I only develop on a Mac so this was a bit of an oversight. I just pushed a change that should fix this!
