### ISSUE TITLE
Youtube search not working

### ISSUE THREAD

**Issue by TexasThrowback** [BobNisco/Spotlistr#37]
When searching youtube playlists I just get stuck at 'searching'. No adblock, multiple devices, tried clearing cookies etc. Not sure if this is a known issue or something weird on my end. Any help appreciated! I really love this tool. It is by far the best playlist converter out there so I hope I can get it to work again...

**Comment by BobNisco** [comment]
Hi @TexasThrowback ! Thanks for reporting this issue. Please go ahead and try it again, as I have fixed the bug here https://github.com/BobNisco/Spotlistr/commit/5d7503e9f741a2ded47189934b2efbbbd5816021 and deployed it
