### ISSUE TITLE
Creates playlist out of order

### ISSUE THREAD

**Issue by kavun** [BobNisco/Spotlistr#38]
When creating via https://www.spotlistr.com/search/lastfm-top-for-time-period, the playlist in Spotify does not mirror the order of the track found by Spotlistr.

As an example, here the first track is by Clarence, but the first track in the generated playlist is not
![image](https://user-images.githubusercontent.com/662069/50834465-af706680-1319-11e9-9762-605c6f21a7c5.png)
![image](https://user-images.githubusercontent.com/662069/50834485-bbf4bf00-1319-11e9-9f86-1eff88ae65d6.png)

**lastfm user**: kevinareed
**date range**: 12/01/2018 - 12/31/2018
**resulting playlist**: https://open.spotify.com/user/kavun/playlist/391YdZgbLipKhkKUTGrIZD?si=LP52UiiZQsaF56EeBoOwYw

**Comment by gordonjb** [comment]
Hi, I also tweeted about this issue a month or two ago, I checked out the repo to have a look at what might be wrong, and order is getting preserved for me there! (Which seems to be a different version from that running on spotlistr.com at the moment)

**Comment by gordonjb** [comment]
Actually, I take that back, I tried the repo version with a larger playlist and order was not preserved.

**Comment by b-oliveira82** [comment]
Same problem here, that fixed would be great.

**Comment by BobNisco** [comment]
Hey all, this should be fixed as of Jan 25, 2020: https://twitter.com/spotlistr/status/1221180887963860993 Thanks a bunch for the report!
