### ISSUE TITLE
Can we get a dump of all playlists?

### ISSUE THREAD

**Issue by haveaguess** [BobNisco/Spotlistr#5]
Would be cool :)

**Comment by BobNisco** [comment]
Hey @haveaguess, thanks for the suggestion. Just to clarify, are you asking for a function that reads in all of your playlists and puts them into a single playlist or just outputs it as plaintext or something slightly different?

**Comment by haveaguess** [comment]
Hiya

Im just thinking if I ever leave it would be great to have a copy of all my tunes per playlist per playlist folder so I can start feeding them into the new service (probably Google Play Music if anything) 

Im so sick of being paywalled by Spotify, it's criminal! 

Just had a go on the youtube playlist importer - very neat! Kinda bugged me how it required me to open each track in the web player, didnt find a good work flow from getting them all into a playlist in spotify but I might have missed a call to action somewhere

Thanks for your work

**Comment by Drew3D** [comment]
Agreed with @haveaguess. It would be very useful to be able to export all of my playlists (or a selection of them) into a CSV/tab-delimited file with artist, title, Spotify Track ID, and maybe even other track info like track length, popularity, and explicit flag.

This would be useful for processing the playlists with external utilities, bringing them into other services, or simply having a backup of my heavily-curated playlists.

Many thanks for your excellent Spotify utilities!

**Comment by BobNisco** [comment]
Hey @haveaguess @Drew3D I just updated it so that you can export a playlist with various parameters and separators. Have a look! http://spotlistr.herokuapp.com/#/export/spotify-playlist
