### ISSUE TITLE
Youtube Playlist search not working

### ISSUE THREAD

**Issue by hindsc52** [BobNisco/Spotlistr#9]
It is just stuck on 'Searching' when trying this playlist: https://www.youtube.com/playlist?list=PLWTkQFAXQh3im2_d5yCN0tglk0OURP8NF

I have tried in both Chrome and Edge

**Comment by BobNisco** [comment]
Hey @hindsc52, I can't seem to repro this. I just tried it on Chrome and it worked without issue. Do you have any sort of adblock enabled?

**Comment by hindsc52** [comment]
Hi I just tried it again in chrome and it has worked fine.

**Comment by littlewilly** [comment]
Same issue for the last 30mins. Tried on 2 different devices (pc & android) without adblock.
